title = "David Haro"
baseURL = "https://printholamundo.github.io/website/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "**Software Engineer**\nDurango, Mexico  \n**Contact:** jdohca@gmail.com"
  codePenUser = "David Haro"

